version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: smartspend_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-smartspend}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-smartspend123}
      POSTGRES_DB: ${POSTGRES_DB:-smartspend}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smartspend"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: smartspend_backend
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-smartspend}:${POSTGRES_PASSWORD:-smartspend123}@postgres:5432/${POSTGRES_DB:-smartspend}
      SECRET_KEY: ${SECRET_KEY:-dev-secret-key-change-in-production}
      UPLOAD_DIR: /app/uploads
      MAX_UPLOAD_SIZE_MB: 20
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: smartspend_frontend
    environment:
      VITE_API_URL: http://localhost:8000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm run dev -- --host

volumes:
  postgres_data:
